name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a33af73e7d10e370dc9412b0e0981a94a9c9d37825d361dd6ca3cc12bd0879be"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
