name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "995a4ca90d6ea2103a78bfd65d0b434b480d33be555487598a04662ca3ceb605"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
