name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "041c9c4c3446fbcb9109a6d6778bc2d3f177bf141a1af497ab2bc4b4d59d8a75"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
