name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7f3b5087035063f730be4907d05db371c1e1b2d6833789b2c9ce087e35e4032"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
