name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bb0750878ceee76033fcc49b57314bdd49261406bd11acfee8ef79265d60761"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
