name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db5d7cd556b9a2004047a7376576ef55217a857997f5e7731b177eefe05e064"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
