name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94b47c56acd1e7b053496d15a3eaa5df5e5fe2a93a4fa5237ae5e7bbca54cb17"

[versions]
minecraft = "1.19.2"
quilt = "0.17.3"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
