name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bb67eb680d745149a51e4e419b00671122fe5da2373dd081ad8d471b22bf977"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"
