name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "021553fc8f6382ccfa0a0834cb8955c37856c592f34ed20da5f71eab93b71a42"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
