name = "Meme 5 Client"
author = "Fauli1221"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbd93714863c12cc93785aeaad740cb236a9633970979bc064be83475bb57a61"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
