name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5835b65bfc8905b9ff0c1d72e1cd49c171dba697cd8ba237514caf6f0a7ca7c"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
