name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e60dce01559a6fec23f97ece8f0ea0e02086dcbcea957bbfc81924973d197d7b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
