name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fb53cd539a76d2f11e6f17a17b2062d1c40a28e3f1e7275a0b3988dbb82fcb4"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
