name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5df6c5d4dbfaf06eda6c90080c8dd2e8d6d0e1fca60294d6f399d74b402f9664"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
