name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41249d925deecaf8ab43144974180c614cab1717c3669cd352cc6dd3c75bf35a"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
