name = "Meme 5 Client"
author = "Fauli1221"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "586e3c8df01477a9b5909f8d5b893de2751fcea1a16f6d9c1612a9177a836a01"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
