name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbf334574d6063ef87fa8ddefdca3dab50ddca3ab9983956b238623a88f34438"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
