name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd2eef900207cd91b79c1e94a735ea233f8d705ff0733f3e3da97315291ea9bf"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
