name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dff7b7b5093ecaf774444a7e240626ada06cc3ce6f0db9409ec2006a9dc4e1fd"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
