name = "Meme 5 Client"
author = "Fauli1221"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d99d3802f41596262b4b34741f4d35527bc0d81fec91f82f91bc34de25790c4d"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
