name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a465a4c3c791d334ef582f4b95dedeba2873eeaf9ef503f844649f3d6869c07"

[versions]
minecraft = "1.19.2"
quilt = "0.17.1"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
