name = "Meme 5 Client"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06c70db43f55cd308ca5de8a830051ac80303dba6dd9bdf334ed8544b3493169"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
