name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ade723cf689068b9e47cd91473c9acabd323b264bb514cf43750a6e171873df"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
