name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11efefe5c112c86f907ce161bc465472c7e08970e3fe339d2323e2af41e19a94"

[versions]
minecraft = "1.19.2"
quilt = "0.17.3"

[options]
acceptable-game-versions = ["1.19.1"]
