name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4901a94819f1f087127dfb11dd8f0b724dacdf91df642233a28d27959bbccf5"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
