name = "Meme 5 Client"
author = "Fauli1221"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd13c1a11339de2266ac32e9bb00826a93f334a81f382b5d2792993dc55e1f46"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
