name = "Meme 5 Client"
author = "Fauli1221"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db21c4fa1ec8d2d8f62231dd3a24a3d89c8abbf90e3609d33f3bee83217d4db"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
