name = "Meme 5 Client"
author = "Fauli1221"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91b8cbfac270cd72fcf16e2650f3647d01a10c3310185cf5103f9c09506a02fd"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
