name = "HD Skins"
filename = "hdskins-6.6.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/FzE9gshV/versions/6.6.0/hdskins-6.6.0.jar"
hash-format = "sha1"
hash = "d706d7a4df654ad89c3c61caa0a368ca79c199de"

[update]
[update.modrinth]
mod-id = "FzE9gshV"
version = "WnP4wWyH"
