name = "Logical Zoom"
filename = "logical_zoom-0.0.16.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "563005a0be19f268f3bb2a9937ef5e7e0abe6bd9"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3910206
project-id = 356461
