name = "Mine Little Pony"
filename = "minelittlepony-4.5.1-dev.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/JBjInUXM/versions/4.5.1/minelittlepony-4.5.1-dev.jar"
hash-format = "sha1"
hash = "37f94c716e9c34cbb2673bb13c6f949389783def"

[update]
[update.modrinth]
mod-id = "JBjInUXM"
version = "3YsZnuUk"
