name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.2-2.3.5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/quilt-1.19.2-2.3.5/voicechat-quilt-1.19.2-2.3.5.jar"
hash-format = "sha1"
hash = "77716682326fb6e64017e5291aed64ba9029f525"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "xTvjbKVQ"

[option]
optional = true
description = "Adds a ingame proximity voicechat compadible with Sound Physics Remastered"
