name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.2-2.2.43.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.43/voicechat-fabric-1.18.2-2.2.43.jar"
hash-format = "sha1"
hash = "13bd207f906010c3e57bb7c3d4da734a629b4440"
mode = ""

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "wZAOmVzE"

[option]
optional = true
description = "Adds a ingame proximity voicechat compadible with Sound Physics Remastered"
