name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.2-2.3.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/quilt-1.19.2-2.3.2/voicechat-quilt-1.19.2-2.3.2.jar"
hash-format = "sha1"
hash = "df41716b2da00fa8c99b07dd4d72284ef0eaf628"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "qykDrhK5"

[option]
optional = true
description = "Adds a ingame proximity voicechat compadible with Sound Physics Remastered"
