name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.2-2.3.7.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/KSTZBh0m/voicechat-quilt-1.19.2-2.3.7.jar"
hash-format = "sha1"
hash = "77d46367f081b211b321a72ea7c53ee3c696b977"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "KSTZBh0m"

[option]
optional = true
description = "Adds a ingame proximity voicechat compadible with Sound Physics Remastered"
