name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.2-2.3.11.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/Pi2VjFQ5/voicechat-quilt-1.19.2-2.3.11.jar"
hash-format = "sha1"
hash = "cc491b6cd44f66761c07fe0b339ff5c19a44ddce"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "Pi2VjFQ5"

[option]
optional = true
description = "Adds a ingame proximity voicechat compadible with Sound Physics Remastered"
