name = "Sound Physics Remastered"
filename = "soundphysics-fabric-1.19-1.0.8.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "93da152745a442ee7859ce338c4dab4ad3f04fe7"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3871765
project-id = 535489

[option]
optional = true
description = "Adds soundphysics I recomend using it with Simple Voice Chat"
