name = "Sound Physics Remastered"
filename = "soundphysics-fabric-1.19.2-1.0.11.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "837fbd0828197c137d1d092c40d0c59947d02fbf"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3920857
project-id = 535489

[option]
optional = true
description = "Adds soundphysics I recomend using it with Simple Voice Chat"
